#!/usr/bin/env bash

function info() {
  echo -e "\n >>>>> $1\n"
}

function run_pylint() {
  cd /home/webapp
  python3 -m pylint $1
}

function cmd_lint() {
  run_pylint core
  run_pylint webui
  run_pylint util
}

function run_mypy() {
  cd /home/webapp
  python3 -m mypy $1
}

function cmd_type() {
  run_mypy .
}

function cmd_test() {
  cd /home/webapp

  if [ -z ${1+x} ]; then
    tests=$(ls -1 tests/test-*.py)
    for test in $tests
    do
      # Remove the extension and replace directory separator with a period
      no_extension=${test%%.*}
      module=${no_extension/\//.}

      echo "Running $module"
      python3 -m $module
    done
  else
    echo "Running $1"
    python3 -m $1
  fi
}

case "$1" in
  "check")
    case "$2" in
      "lint")
        info "Start lint checks ..."
        cmd_lint
        ;;

      "type")
        info "Start type checks ..."
        cmd_type
        ;;

      *)
        echo -e "\nUsage:";
        echo "  $script app check [COMMAND]";
        echo -e "\nCommands:";
        echo "  lint      Run the python linter";
        echo "  type      Run the python static type checker";
        ;;
    esac
    ;;

  "test")
    cmd_test ${@:2}
    ;;

  *)
    echo -e "\nUsage:";
    echo "  $script [COMMAND]";
    echo -e "\nCommands:";
    echo "  check     Run various checks against the code";
    echo "  test [m]  Run all the unit tests or just module 'm'";
    ;;
esac
