#!/usr/bin/env bash

function cmd_lint() {
  cd /home/webapp
  python3 -m pylint webapp
}

function cmd_test() {
  cd /home/webapp
  tests=$(ls -1 tests/*.py)
  for test in $tests
  do
    # Remove the extension and replace directory separator with a period
    no_extension=${test%%.*}
    module=${no_extension/\//.}

    echo "Running $module"
    python3 -m $module
  done
}

case "$1" in
  "lint")
    cmd_lint
    ;;

  "test")
    cmd_test
    ;;

  *)
    echo -e "\nUsage:";
    echo "  $script [COMMAND]";
    echo -e "\nCommands:";
    echo "  lint      Run the static code analysis (linter) against the code";
    echo "  test      Run the unit tests";
    ;;
esac
