version: '3.7'

services:

  reverse_proxy:
    image: nginx:1.19.0
    container_name: ${REVERSE_PROXY_SERVER_NAME}
    restart: always
    volumes:
      - './reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
      - ${HOST_HTTP_PORT}:80
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - application

  application:
    build: ./application
    container_name: ${APPLICATION_SERVER_NAME}
    restart: always
    volumes:
        - './application:/home/webapp'
    environment:
        # Do not set this variable if you do not want real-time changes to take
        # effect. Note: This expects the volume to be used as well!
      - RELOAD_ARG=--reload
      - APP_CONFIG=${APP_CONFIG}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - sql_database

  sql_database:
    image: postgres:12.3
    container_name: ${SQL_DATABASE_SERVER_NAME}
    restart: always
    volumes:
      - './data/postgresql:/var/lib/postgresql/data'
    networks:
      - ${NETWORK_NAME}

  sql_adminstration:
    image: adminer:4.7.7
    container_name: ${SQL_ADMINISTRATION_SERVER_NAME}
    restart: always
    ports:
      - ${HOST_SQL_ADMIN_PORT}:8080
    environment:
      # Avaialble designs: https://github.com/vrana/adminer/tree/master/designs
      - ADMINER_DESIGN=nette
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - sql_database

networks:
  webapp_network:
    name: ${NETWORK_NAME}
    driver: bridge
