version: '3.7'

services:

  proxy:
    build: ./reverse-proxy
    container_name: webapp_proxy
    restart: always
    ports:
      - 8000:80

  application:
    build: ./application
    container_name: webapp_application
    restart: always
    volumes:
        - './application:/home/webapp'
    environment:
        # Unbuffer gunicorn log output so that it's real-time
        PYTHONUNBUFFERED: 'true'

        # Do not set this variable if you do not want real-time changes to take
        # effect. Note: This expects the volume to be used as well!
        RELOAD_ARG: '--reload'
