version: '3.7'

services:

  proxy:
    image: nginx:1.19.0
    container_name: ${WEBAPP}_proxy
    restart: always
    volumes:
      - './reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
      - ${HOST_HTTP_PORT}:80

  application:
    build: ./application
    container_name: ${WEBAPP}_application
    restart: always
    volumes:
        - './application:/home/webapp'
    environment:
        # Unbuffer gunicorn log output so that it's real-time
        PYTHONUNBUFFERED: 'true'

        # Do not set this variable if you do not want real-time changes to take
        # effect. Note: This expects the volume to be used as well!
        RELOAD_ARG: '--reload'
