version: '3.7'

services:

  reverse_proxy:
    image: nginx:1.19.10
    container_name: ${REVERSE_PROXY_SERVER_NAME}
    restart: always
    volumes:
      - './reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
      - ${HOST_HTTP_PORT}:80
    depends_on:
      - application

  application:
    image: ${COMPOSE_PROJECT_NAME}/application:1.1
    build: ./application
    container_name: ${APPLICATION_SERVER_NAME}
    restart: always
    volumes:
        - './application:/home/webapp'
    env_file:
      - .env
    environment:
      - LOG_LEVEL
        # Do not set this variable if you do not want real-time changes to take
        # effect. Note: This expects the volume to be used as well!
      - RELOAD_ARG=--reload
      - CONFIG_STRATEGY
    depends_on:
      - sql_database

  sql_database:
    image: postgres:12.7
    container_name: ${SQL_DATABASE_SERVER_NAME}
    restart: always
    volumes:
      - './data/postgresql:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  sql_administration:
    image: adminer:4.8.0
    container_name: ${SQL_ADMINISTRATION_SERVER_NAME}
    restart: always
    ports:
      - ${HOST_SQL_ADMIN_PORT}:8080
    environment:
      # Avaialble designs: https://github.com/vrana/adminer/tree/master/designs
      - ADMINER_DESIGN=nette
    depends_on:
      - sql_database

networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge
