#!/bin/bash
#
# This script prepares this repository for consumption in your own project.
#
script=$0

git -C . rev-parse &> /dev/null
git_cmd_retcode=$?

if [ $git_cmd_retcode -ne 0 ]; then
  echo "$script is intended to be run at the root of the project as a repository."
else
  echo "Removing tracked secrets from repository cache..."
  git rm --cached secrets/postgres_user.txt
  git rm --cached secrets/postgres_password.txt
  git rm --cached application/secrets/settings.py
  echo ""

  echo "Removing LICENSE file..."
  git rm LICENSE

  echo "Removing $script..."
  git rm $script

  echo ""
  echo "You may now safely commit the staged changes :)"
fi
